### ISSUE TITLE
build + context or external URI

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-compose#2]
I'm starting with requiring a build and a context:

```
  nginx:
    build:
      context: ./nginx
      recipe: Singularity.nginx
...
```
and it should also be possible to provide an image unique resource identifier (to just be pulled)

```
  nginx:
    image: docker://nginx
...
```
