### ISSUE TITLE
No way to run persistent containers

### ISSUE THREAD

**Issue by briveramelo** [singularityhub/singularity-compose#43]
Continuing from the recent addition to support run, exec, network options [https://github.com/singularityhub/singularity-compose/issues/38#issuecomment-796659715](https://github.com/singularityhub/singularity-compose/issues/38#issuecomment-796659715), I ran into an issue with running persistent containers.

I am running web service containers, so I have a database container and a web server container that each must run persistently. I would like to run a command like `singularity-compose up` and have both containers start up to run the web site, but instead the database will start and block the web server from starting. My workaround for now is a small shell script that backgrounds each service one after another with a separate command for each.

Here is a sample singularity-compose.yml for testing. It's not a direct matchup with the above example, but you will encounter the same issue.

```
version: "2.0"

instances:

  alp1:
    image: alpine/alpine.sif
    ports:
      - "1025:1025"
    start:
      options:
        - e
        - C
        - f
        - w
    exec:
      options:
        - e
        - C
      command: "echo 'alp1 in the house'"
  
  alp2:
    image: alpine/alpine.sif
    ports:
      - "1026:1026"
    start:
      options:
        - e
        - C
        - f
        - w
    exec:
      options:
        - e
        - C
      command: "ping alp1"
    run:
      args:
        - echo
        - 'this will never print because of the perpetual ping'
``` 

I wonder if we can provide an option in the yml to run the command in the background. I have tried workarounds like passing cli redirects through the command options, but I have no success. For example
```
...
exec:
      options:
        - e
        - C
      command: "ping alp1 >& /dev/null &"
...
```
subprocess.CalledProcessError: Command '['singularity', 'exec', '-e', '-C', 'instance://alp3', 'ping', 'alp2', '>&', '/dev/null', '&']' returned non-zero exit status 1.

So something like this could help
```
...
exec:
      background: true
...
```

The places I see this applying are with start, exec, and run, as I believe all 3 can take commands and have the potential to hang up other containers.

This line seems to execute the commands of interest and prevent subsequent actions / containers from running.
[https://github.com/singularityhub/singularity-compose/blob/570388ed3144deabb3e0acc659dc3f797f4f051c/scompose/project/project.py#L489](https://github.com/singularityhub/singularity-compose/blob/570388ed3144deabb3e0acc659dc3f797f4f051c/scompose/project/project.py#L489)

Am I missing an alternate way to background these, or is this worth pursuing? I'm open to alternate approaches.

I hope the delay in writing this up hasn't been too long! Thanks again for your help supporting the fakeroot network and other options with the previous issue

**Comment by vsoch** [comment]
For the order, you can try depends_on: https://github.com/singularityhub/singularity-compose/blob/f8897e107ab7cbba3c6656486a132aeb0699ad35/scompose/tests/configs/depends_on/singularity-compose.yml

**Comment by vsoch** [comment]
@briveramelo for the background issue, I would approach the singularity community or sylabs and ask how it could be done. If there is a way, we can then implement it here.

**Comment by briveramelo** [comment]
> For the order, you can try depends_on: https://github.com/singularityhub/singularity-compose/blob/f8897e107ab7cbba3c6656486a132aeb0699ad35/scompose/tests/configs/depends_on/singularity-compose.yml

Yes, I am familiar with this. I neglected it in this example, but this is not an issue for me.



> @briveramelo for the background issue, I would approach the singularity community or sylabs and ask how it could be done. If there is a way, we can then implement it here.

I did some investigation, and all the examples suggest this redirection method I mentioned above. I'll still ask around if there are alternate methods that might integrate more closely with the singularity cli and report back here

**Comment by briveramelo** [comment]
I tried a suggestion to add the persistent command to the start args. Apparently this runs to the background by default: [https://github.com/hpcng/singularity/issues/5891#issuecomment-806934104](https://github.com/hpcng/singularity/issues/5891#issuecomment-806934104)

However, this does not appear to be working with singularity compose. I've tried a few different things to test if the start args are ever called. Eg: printing the logs, setting the start args to create a file and then using the exec command to print out the contents of the directory where it should have been created. These tests are showing me the start args are never called.

I think there may be a line missing in the instance create function to calls the start args:
[https://github.com/singularityhub/singularity-compose/blob/570388ed3144deabb3e0acc659dc3f797f4f051c/scompose/project/instance.py#L546-L557](https://github.com/singularityhub/singularity-compose/blob/570388ed3144deabb3e0acc659dc3f797f4f051c/scompose/project/instance.py#L546-L557)

**Comment by briveramelo** [comment]
This should be a sufficient yaml example to test that the start args are called:

singularity-compose.yml
```
version: "2.0"

instances:

  alp:
    image: alpine/alpine.sif
    start:
      options:
        - e
        - C
        - w
      args: "touch file1.txt"
    exec:
      options:
        - e
        - C
      command: "ls"
```

And if it works, you should see file1.txt printed out in the list when running 
`singularity-compose up`
