### ISSUE TITLE
Runscript as background process

### ISSUE THREAD

**Issue by jadraketx** [singularityhub/singularity-compose#58]
singularity-compose has been a great resource, thanks! I'm trying to launch 9 containers pulled from Docker images on an HPC system. Container 1 (server) needs to launch first, then Container 2, and then Containers 3-9 (no order). As these are docker images, there is no startscript so I need to run each containers runscript (i.e. docker entrypoint).  In the singularity-compose.yaml config, I have included the run group for Container 1. When running singularity-compose up, Container 1 instance starts properly and the runscript is executed but it hangs here and does not proceed to launch the other containers. I believe this is due to the default behavior of Container 1, which launches the server and logs to stdout. Ideally, I would like to launch the runscript as a background process (e.g. singularity run instance://container1 &). Is it possible to specify this within the config file? Thanks!

**Comment by vsoch** [comment]
Oh interesting! I don't see why not. Do you have a dummy case we could add to https://github.com/singularityhub/singularity-compose-examples for me to develop with (and reproduce your error) and be able to provide the example for future users?

**Comment by jadraketx** [comment]
A simple example would be launching a docker container that runs a jupyter notebook/server. 

```
version: "2.0"
instances:
  jupyter:
    image: docker://umids/jupyterlab
    volumes:
       - /usr/work:/usr/local/share/jupyter/lab/settings/
    network:
       enable: false
    run: []
```
To launch the server, the runscript must be executed. Any other instances included after "jupyter" in the config file won't be launched. I think a workaround would be to create a definition file that bootstraps from this image and then add a startscript that runs the same command as the docker entrypoint. However, in our case users don't have sudo permission to build from a def file which is why it'd just be easier to launch as a bg process.

**Comment by vsoch** [comment]
If you are interested, this is pretty early in development but I'm making a framework called "tunel" (elegant form of tunnel) that already has support for notebooks / jupyterlab:

- https://vsoch.github.io/tunel
- https://vsoch.github.io/tunel/_static/apps/

I'm in the process of designing underlying templates so developers can make custom apps. It's a personal project so it's not moving as quick as other stuffs, but it's coming along!

**Comment by vsoch** [comment]
Does this run on a port? Which one?

**Comment by jadraketx** [comment]
It runs on localhost:8888

**Comment by vsoch** [comment]
okay so this works for me:

```yaml
version: "2.0"
instances:
  jupyter:
    image: docker://umids/jupyterlab
    volumes:
       - ./work:/usr/local/share/jupyter/lab/settings/
    ports:
      - 8888:8888
    run: []
```
You are saying we should add another container before or after? Could you provide an example of that?
